import type { ResumeDoc } from "@/lib/resume-doc";

/**
 * Resume document → LaTeX source.
 *
 * Pure string templating; no compiler is involved and none is bundled. The
 * output is a self-contained .tex file that compiles in Overleaf or any local
 * TeX install, which is the escape hatch for anyone who wants TeX-grade
 * typesetting or wants to hand-tune the layout.
 */

/**
 * LaTeX's special characters, escaped so resume text cannot break the build.
 *
 * `|`, `<` and `>` are legal in text mode but render as the wrong glyph (a
 * pipe comes out as an em-dash), so they are mapped to their text commands
 * rather than left alone — contact lines and skill lists use pipes freely.
 */
function esc(raw: string): string {
  return raw
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
    .replace(/\|/g, "\\textbar{}")
    .replace(/</g, "\\textless{}")
    .replace(/>/g, "\\textgreater{}");
}

export function toLatex(doc: ResumeDoc): string {
  const { contact } = doc;
  const out: string[] = [];

  out.push(
    String.raw`% Generated by Resume Optimizer — persona: ${doc.personaName}
% Compiles as-is in Overleaf (pdfLaTeX). Content comes from the corpus;
% edit there rather than here, or this file will be overwritten on re-export.
\documentclass[letterpaper,10pt]{article}
\usepackage[margin=0.5in]{geometry}
\usepackage{enumitem}
\usepackage{titlesec}
\usepackage[hidelinks]{hyperref}
\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault}
\pagestyle{empty}
\setlength{\parindent}{0pt}

\titleformat{\section}{\large\bfseries}{}{0em}{}[\vspace{-0.6em}\rule{\linewidth}{0.6pt}]
\titlespacing{\section}{0pt}{8pt}{4pt}

\newcommand{\entry}[2]{\textbf{#1}\hfill{\small #2}\par}
\newcommand{\meta}[1]{{\small #1}\par}

\begin{document}
`,
  );

  // Header
  out.push(String.raw`\begin{minipage}[t]{0.55\textwidth}
{\LARGE\bfseries ${esc(contact.name.toUpperCase())}}\par
${contact.location ? `{\\small ${esc(contact.location)}}` : ""}
\end{minipage}%
\begin{minipage}[t]{0.45\textwidth}
\raggedleft\small
${esc([contact.phone, contact.email].filter(Boolean).join(" | "))}\\
${contact.links
    .map((l) => esc(l.url.replace(/^https?:\/\//, "")))
    .join("\\\\\n")}
\end{minipage}
\vspace{4pt}
`);

  for (const section of doc.sections) {
    out.push(String.raw`\section*{${esc(section.label)}}`);

    if (section.type === "skills") {
      out.push(String.raw`\begin{itemize}[leftmargin=*,nosep,label={}]`);
      for (const g of section.groups) {
        out.push(
          String.raw`  \item \textbf{${esc(g.label)}:} ${esc(g.items.join(", "))}`,
        );
      }
      out.push(String.raw`\end{itemize}`);
      continue;
    }

    if (section.type === "inline") {
      out.push(esc(section.items.join("  |  ")) + String.raw`\par`);
      continue;
    }

    for (const e of section.entries) {
      const heading = e.org ? `${e.title} — ${e.org}` : e.title;
      out.push(String.raw`\entry{${esc(heading)}}{${esc(e.dateRange)}}`);

      const meta = [e.orgDescriptor, e.location].filter(Boolean).join(" · ");
      if (meta) out.push(String.raw`\meta{${esc(meta)}}`);
      if (e.tagline) out.push(String.raw`\meta{\textit{${esc(e.tagline)}}}`);

      if (e.bullets.length) {
        out.push(String.raw`\begin{itemize}[leftmargin=1.2em,nosep,topsep=2pt]`);
        for (const b of e.bullets) {
          out.push(String.raw`  \item ${esc(b.text)}`);
        }
        out.push(String.raw`\end{itemize}`);
      }
      out.push(String.raw`\vspace{3pt}`);
    }
  }

  out.push(String.raw`\end{document}`);
  return out.join("\n");
}
